/**
 *  Copyright (C) 2024 Louka Ménard Blondin
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

export default [
  {
    id: 1,
    name: "الفاتحة",
    transliteration: "Al-Fatihah",
    translation: "The Opener",
  },
  {
    id: 2,
    name: "البقرة",
    transliteration: "Al-Baqarah",
    translation: "The Cow",
  },
  {
    id: 3,
    name: "آل عمران",
    transliteration: "Ali 'Imran",
    translation: "Family of Imran",
  },
  {
    id: 4,
    name: "النساء",
    transliteration: "An-Nisa",
    translation: "The Women",
  },
  {
    id: 5,
    name: "المائدة",
    transliteration: "Al-Ma'idah",
    translation: "The Table Spread",
  },
  {
    id: 6,
    name: "الأنعام",
    transliteration: "Al-An'am",
    translation: "The Cattle",
  },
  {
    id: 7,
    name: "الأعراف",
    transliteration: "Al-A'raf",
    translation: "The Heights",
  },
  {
    id: 8,
    name: "الأنفال",
    transliteration: "Al-Anfal",
    translation: "The Spoils of War",
  },
  {
    id: 9,
    name: "التوبة",
    transliteration: "At-Tawbah",
    translation: "The Repentance",
  },
  {
    id: 10,
    name: "يونس",
    transliteration: "Yunus",
    translation: "Jonah",
  },
  {
    id: 11,
    name: "هود",
    transliteration: "Hud",
    translation: "Hud",
  },
  {
    id: 12,
    name: "يوسف",
    transliteration: "Yusuf",
    translation: "Joseph",
  },
  {
    id: 13,
    name: "الرعد",
    transliteration: "Ar-Ra'd",
    translation: "The Thunder",
  },
  {
    id: 14,
    name: "ابراهيم",
    transliteration: "Ibrahim",
    translation: "Abraham",
  },
  {
    id: 15,
    name: "الحجر",
    transliteration: "Al-Hijr",
    translation: "The Rocky Tract",
  },
  {
    id: 16,
    name: "النحل",
    transliteration: "An-Nahl",
    translation: "The Bee",
  },
  {
    id: 17,
    name: "الإسراء",
    transliteration: "Al-Isra",
    translation: "The Night Journey",
  },
  {
    id: 18,
    name: "الكهف",
    transliteration: "Al-Kahf",
    translation: "The Cave",
  },
  {
    id: 19,
    name: "مريم",
    transliteration: "Maryam",
    translation: "Mary",
  },
  {
    id: 20,
    name: "طه",
    transliteration: "Taha",
    translation: "Ta-Ha",
  },
  {
    id: 21,
    name: "الأنبياء",
    transliteration: "Al-Anbya",
    translation: "The Prophets",
  },
  {
    id: 22,
    name: "الحج",
    transliteration: "Al-Hajj",
    translation: "The Pilgrimage",
  },
  {
    id: 23,
    name: "المؤمنون",
    transliteration: "Al-Mu'minun",
    translation: "The Believers",
  },
  {
    id: 24,
    name: "النور",
    transliteration: "An-Nur",
    translation: "The Light",
  },
  {
    id: 25,
    name: "الفرقان",
    transliteration: "Al-Furqan",
    translation: "The Criterion",
  },
  {
    id: 26,
    name: "الشعراء",
    transliteration: "Ash-Shu'ara",
    translation: "The Poets",
  },
  {
    id: 27,
    name: "النمل",
    transliteration: "An-Naml",
    translation: "The Ant",
  },
  {
    id: 28,
    name: "القصص",
    transliteration: "Al-Qasas",
    translation: "The Stories",
  },
  {
    id: 29,
    name: "العنكبوت",
    transliteration: "Al-'Ankabut",
    translation: "The Spider",
  },
  {
    id: 30,
    name: "الروم",
    transliteration: "Ar-Rum",
    translation: "The Romans",
  },
  {
    id: 31,
    name: "لقمان",
    transliteration: "Luqman",
    translation: "Luqman",
  },
  {
    id: 32,
    name: "السجدة",
    transliteration: "As-Sajdah",
    translation: "The Prostration",
  },
  {
    id: 33,
    name: "الأحزاب",
    transliteration: "Al-Ahzab",
    translation: "The Combined Forces",
  },
  {
    id: 34,
    name: "سبإ",
    transliteration: "Saba",
    translation: "Sheba",
  },
  {
    id: 35,
    name: "فاطر",
    transliteration: "Fatir",
    translation: "Originator",
  },
  {
    id: 36,
    name: "يس",
    transliteration: "Ya-Sin",
    translation: "Ya Sin",
  },
  {
    id: 37,
    name: "الصافات",
    transliteration: "As-Saffat",
    translation: "Those who set the Ranks",
  },
  {
    id: 38,
    name: "ص",
    transliteration: "Sad",
    translation: 'The Letter "Saad"',
  },
  {
    id: 39,
    name: "الزمر",
    transliteration: "Az-Zumar",
    translation: "The Troops",
  },
  {
    id: 40,
    name: "غافر",
    transliteration: "Ghafir",
    translation: "The Forgiver",
  },
  {
    id: 41,
    name: "فصلت",
    transliteration: "Fussilat",
    translation: "Explained in Detail",
  },
  {
    id: 42,
    name: "الشورى",
    transliteration: "Ash-Shuraa",
    translation: "The Consultation",
  },
  {
    id: 43,
    name: "الزخرف",
    transliteration: "Az-Zukhruf",
    translation: "The Ornaments of Gold",
  },
  {
    id: 44,
    name: "الدخان",
    transliteration: "Ad-Dukhan",
    translation: "The Smoke",
  },
  {
    id: 45,
    name: "الجاثية",
    transliteration: "Al-Jathiyah",
    translation: "The Crouching",
  },
  {
    id: 46,
    name: "الأحقاف",
    transliteration: "Al-Ahqaf",
    translation: "The Wind-Curved Sandhills",
  },
  {
    id: 47,
    name: "محمد",
    transliteration: "Muhammad",
    translation: "Muhammad",
  },
  {
    id: 48,
    name: "الفتح",
    transliteration: "Al-Fath",
    translation: "The Victory",
  },
  {
    id: 49,
    name: "الحجرات",
    transliteration: "Al-Hujurat",
    translation: "The Rooms",
  },
  {
    id: 50,
    name: "ق",
    transliteration: "Qaf",
    translation: 'The Letter "Qaf"',
  },
  {
    id: 51,
    name: "الذاريات",
    transliteration: "Adh-Dhariyat",
    translation: "The Winnowing Winds",
  },
  {
    id: 52,
    name: "الطور",
    transliteration: "At-Tur",
    translation: "The Mount",
  },
  {
    id: 53,
    name: "النجم",
    transliteration: "An-Najm",
    translation: "The Star",
  },
  {
    id: 54,
    name: "القمر",
    transliteration: "Al-Qamar",
    translation: "The Moon",
  },
  {
    id: 55,
    name: "الرحمن",
    transliteration: "Ar-Rahman",
    translation: "The Beneficent",
  },
  {
    id: 56,
    name: "الواقعة",
    transliteration: "Al-Waqi'ah",
    translation: "The Inevitable",
  },
  {
    id: 57,
    name: "الحديد",
    transliteration: "Al-Hadid",
    translation: "The Iron",
  },
  {
    id: 58,
    name: "المجادلة",
    transliteration: "Al-Mujadila",
    translation: "The Pleading Woman",
  },
  {
    id: 59,
    name: "الحشر",
    transliteration: "Al-Hashr",
    translation: "The Exile",
  },
  {
    id: 60,
    name: "الممتحنة",
    transliteration: "Al-Mumtahanah",
    translation: "She that is to be examined",
  },
  {
    id: 61,
    name: "الصف",
    transliteration: "As-Saf",
    translation: "The Ranks",
  },
  {
    id: 62,
    name: "الجمعة",
    transliteration: "Al-Jumu'ah",
    translation: "The Congregation, Friday",
  },
  {
    id: 63,
    name: "المنافقون",
    transliteration: "Al-Munafiqun",
    translation: "The Hypocrites",
  },
  {
    id: 64,
    name: "التغابن",
    transliteration: "At-Taghabun",
    translation: "The Mutual Disillusion",
  },
  {
    id: 65,
    name: "الطلاق",
    transliteration: "At-Talaq",
    translation: "The Divorce",
  },
  {
    id: 66,
    name: "التحريم",
    transliteration: "At-Tahrim",
    translation: "The Prohibition",
  },
  {
    id: 67,
    name: "الملك",
    transliteration: "Al-Mulk",
    translation: "The Sovereignty",
  },
  {
    id: 68,
    name: "القلم",
    transliteration: "Al-Qalam",
    translation: "The Pen",
  },
  {
    id: 69,
    name: "الحاقة",
    transliteration: "Al-Haqqah",
    translation: "The Reality",
  },
  {
    id: 70,
    name: "المعارج",
    transliteration: "Al-Ma'arij",
    translation: "The Ascending Stairways",
  },
  {
    id: 71,
    name: "نوح",
    transliteration: "Nuh",
    translation: "Noah",
  },
  {
    id: 72,
    name: "الجن",
    transliteration: "Al-Jinn",
    translation: "The Jinn",
  },
  {
    id: 73,
    name: "المزمل",
    transliteration: "Al-Muzzammil",
    translation: "The Enshrouded One",
  },
  {
    id: 74,
    name: "المدثر",
    transliteration: "Al-Muddaththir",
    translation: "The Cloaked One",
  },
  {
    id: 75,
    name: "القيامة",
    transliteration: "Al-Qiyamah",
    translation: "The Resurrection",
  },
  {
    id: 76,
    name: "الانسان",
    transliteration: "Al-Insan",
    translation: "The Man",
  },
  {
    id: 77,
    name: "المرسلات",
    transliteration: "Al-Mursalat",
    translation: "The Emissaries",
  },
  {
    id: 78,
    name: "النبإ",
    transliteration: "An-Naba",
    translation: "The Tidings",
  },
  {
    id: 79,
    name: "النازعات",
    transliteration: "An-Nazi'at",
    translation: "Those who drag forth",
  },
  {
    id: 80,
    name: "عبس",
    transliteration: "'Abasa",
    translation: "He Frowned",
  },
  {
    id: 81,
    name: "التكوير",
    transliteration: "At-Takwir",
    translation: "The Overthrowing",
  },
  {
    id: 82,
    name: "الإنفطار",
    transliteration: "Al-Infitar",
    translation: "The Cleaving",
  },
  {
    id: 83,
    name: "المطففين",
    transliteration: "Al-Mutaffifin",
    translation: "The Defrauding",
  },
  {
    id: 84,
    name: "الإنشقاق",
    transliteration: "Al-Inshiqaq",
    translation: "The Sundering",
  },
  {
    id: 85,
    name: "البروج",
    transliteration: "Al-Buruj",
    translation: "The Mansions of the Stars",
  },
  {
    id: 86,
    name: "الطارق",
    transliteration: "At-Tariq",
    translation: "The Nightcommer",
  },
  {
    id: 87,
    name: "الأعلى",
    transliteration: "Al-A'la",
    translation: "The Most High",
  },
  {
    id: 88,
    name: "الغاشية",
    transliteration: "Al-Ghashiyah",
    translation: "The Overwhelming",
  },
  {
    id: 89,
    name: "الفجر",
    transliteration: "Al-Fajr",
    translation: "The Dawn",
  },
  {
    id: 90,
    name: "البلد",
    transliteration: "Al-Balad",
    translation: "The City",
  },
  {
    id: 91,
    name: "الشمس",
    transliteration: "Ash-Shams",
    translation: "The Sun",
  },
  {
    id: 92,
    name: "الليل",
    transliteration: "Al-Layl",
    translation: "The Night",
  },
  {
    id: 93,
    name: "الضحى",
    transliteration: "Ad-Duhaa",
    translation: "The Morning Hours",
  },
  {
    id: 94,
    name: "الشرح",
    transliteration: "Ash-Sharh",
    translation: "The Relief",
  },
  {
    id: 95,
    name: "التين",
    transliteration: "At-Tin",
    translation: "The Fig",
  },
  {
    id: 96,
    name: "العلق",
    transliteration: "Al-'Alaq",
    translation: "The Clot",
  },
  {
    id: 97,
    name: "القدر",
    transliteration: "Al-Qadr",
    translation: "The Power",
  },
  {
    id: 98,
    name: "البينة",
    transliteration: "Al-Bayyinah",
    translation: "The Clear Proof",
  },
  {
    id: 99,
    name: "الزلزلة",
    transliteration: "Az-Zalzalah",
    translation: "The Earthquake",
  },
  {
    id: 100,
    name: "العاديات",
    transliteration: "Al-'Adiyat",
    translation: "The Courser",
  },
  {
    id: 101,
    name: "القارعة",
    transliteration: "Al-Qari'ah",
    translation: "The Calamity",
  },
  {
    id: 102,
    name: "التكاثر",
    transliteration: "At-Takathur",
    translation: "The Rivalry in world increase",
  },
  {
    id: 103,
    name: "العصر",
    transliteration: "Al-'Asr",
    translation: "The Declining Day",
  },
  {
    id: 104,
    name: "الهمزة",
    transliteration: "Al-Humazah",
    translation: "The Traducer",
  },
  {
    id: 105,
    name: "الفيل",
    transliteration: "Al-Fil",
    translation: "The Elephant",
  },
  {
    id: 106,
    name: "قريش",
    transliteration: "Quraysh",
    translation: "Quraysh",
  },
  {
    id: 107,
    name: "الماعون",
    transliteration: "Al-Ma'un",
    translation: "The Small kindnesses",
  },
  {
    id: 108,
    name: "الكوثر",
    transliteration: "Al-Kawthar",
    translation: "The Abundance",
  },
  {
    id: 109,
    name: "الكافرون",
    transliteration: "Al-Kafirun",
    translation: "The Disbelievers",
  },
  {
    id: 110,
    name: "النصر",
    transliteration: "An-Nasr",
    translation: "The Divine Support",
  },
  {
    id: 111,
    name: "المسد",
    transliteration: "Al-Masad",
    translation: "The Palm Fiber",
  },
  {
    id: 112,
    name: "الإخلاص",
    transliteration: "Al-Ikhlas",
    translation: "The Sincerity",
  },
  {
    id: 113,
    name: "الفلق",
    transliteration: "Al-Falaq",
    translation: "The Daybreak",
  },
  {
    id: 114,
    name: "الناس",
    transliteration: "An-Nas",
    translation: "Mankind",
  },
]
